#pragma config(Motor,  port1,           left1,         tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           left2,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           right1,        tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port10,          right2,        tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	for (;;){
			motor[left1]=VexRT[Ch2];
			motor[left2]=VexRT[Ch2];
			motor[right1]=-VexRT[Ch3];
			motor[right2]=-VexRT[Ch3];
			delay(50);
	}
}
