#pragma config(Motor,  port2,           left1,         tmotorVex393_MC29, openLoop)//Declares to the computer what motors is the robot going to be using
#pragma config(Motor,  port3,           left2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           right1,        tmotorVex393_MC29, openLoop, reversed)//These two motors are reversed because the motors are on backwards.
#pragma config(Motor,  port5,           right2,        tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()//This is a program designed to run a basic car with 4 wheels.
{
	for(;;){//This makes it so that the robot is constantly keeping the motor's speed updated.
		motor[left1] = vexRT[Ch3];//This sets the first left motor to run at whatever speed the left joystick sets it to.
		motor[left2] = vexRT[Ch3];//Same as above but for the second motor
		motor[right1] = vexRT[Ch2];//Same as above, but for the opposite side. As we have already declared that this is a reversed motor, we can treat it the same as the other motors.
		motor[right2] = vexRT[Ch2];
	}
}
