#pragma config(Motor,  port1,           left1,         tmotorVex393_HBridge, openLoop, driveLeft)
#pragma config(Motor,  port2,           left2,         tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port4,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           right1,        tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port10,          right2,        tmotorVex393_HBridge, openLoop, reversed, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
	while(true)
	{
		//left side of the robot is controlled by the right joystick, Y-axis
		motor[left1] = vexRT[Ch3];
		motor[left2] = vexRT[Ch3];
		//righ side of the robot is controlled by the left joystick, Y-axis
		motor[right1] = vexRT[Ch2];
		motor[right2] = vexRT[Ch2];
		//Claw buttons
		if (vexRT[Btn6U])
		{
			motor[claw] = -1;
		}
		else if (vexRT[Btn6D])
		{
			motor[claw] = 1;
		}
		else
		{
			motor[claw] = 0;
		}
	}
}
