#pragma config(Sensor, dgtl11, loadersense,    sensorQuadEncoder)
#pragma config(Motor,  port1,           right1,        tmotorVex393_HBridge, openLoop, driveLeft)
#pragma config(Motor,  port2,           right2,        tmotorVex393_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port3,           intake,        tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port4,           arm,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           left1,         tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port10,          left2,         tmotorVex393_HBridge, openLoop, reversed, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	bool intakeon = false;


	for (;;){

  		if(vexRT[Btn8U] == 1){
    		intakeon = true;
  		}
  		if(vexRT[Btn8D] == 1){
    		intakeon = false;
  		}

			motor[left1]=-vexRT[Ch2];
			motor[left2]=-vexRT[Ch2];

			motor[right1]=vexRT[Ch3];
			motor[right2]=vexRT[Ch3];

			if(intakeon){
    	 motor[intake]=-127;
  		}
  		else{
  			motor[intake]=0;
  		}

  		if(vexRT[Btn7U]){
    	 motor[arm]=100;
  		}
  		else if(vexRT[Btn7D]){
    	 motor[arm]=-100;
  		}
  		else{
  			motor[arm]=0;
  		}

			delay(50);
	}
}
