#pragma config(Sensor, dgtl11, loadersense,    sensorQuadEncoder)
#pragma config(Motor,  port1,           left1,         tmotorVex393_HBridge, openLoop, driveLeft)
#pragma config(Motor,  port2,           left2,         tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           tilt,          tmotorServoStandard, openLoop)
#pragma config(Motor,  port4,           shootr,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           shootl,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           loader,        tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port9,           right1,        tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port10,          right2,        tmotorVex393_HBridge, openLoop, reversed, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	int servopos = 35;
	bool shooteron = false;

	bool fast = true;
	bool reverse = false;

	bool fastpress = false;
	bool reversepress = false;

 	motor[loader] = 0;


	for (;;){

			if(vexRT[Btn5U] == 1 && servopos>-40){
    		servopos -= 1;
  		}
  		if(vexRT[Btn5D] == 1 && servopos < 35){
    	servopos += 1;
  		}

  		if(vexRT[Btn7U] == 1){
    		shooteron = true;
  		}
  		if(vexRT[Btn7D] == 1){
    	shooteron = false;
  		}

  		if(vexRT[Btn6U] == 1 && !fastpress){
    		fast = !fast;
    		fastpress = true;
  		}
  		else if(vexRT[Btn6U] == 0 && fastpress){
  			fastpress = false;
  		}


  		if(vexRT[Btn6D] == 1 && !reversepress){
    		reverse = !reverse;
    		reversepress = true;
  		}
  		else if(vexRT[Btn6D] == 0 && reversepress){
  			reversepress = false;
  		}

  		int left;
  		int right;

  		if(fast) {
  			left = vexRT[Ch2];
  			right = vexRT[Ch3];
  		}
  		else{
  			left = vexRT[Ch2] / 3;
  			right = vexRT[Ch3] / 3 ;
  		}

  		if(!reverse){
				motor[left1]=-left;
				motor[left2]=-left;
				motor[right1]=right;
				motor[right2]=right;
			}
			else{
				motor[left1]=right;
				motor[left2]=right;
				motor[right1]=-left;
				motor[right2]=-left;
			}

			setServo(tilt, servopos);

			if(shooteron){
    	 motor[shootr]=127;
    	 motor[shootl]=127;
  		}
  		else{
  			motor[shootr]=0;
    	 	motor[shootl]=0;
  		}

  		if(vexRT[Btn8U]){
    	 motor[loader]=40;
  		}
  		else if(vexRT[Btn8D]){
    	 motor[loader]=-40;
  		}
  		else{
  			motor[loader]=0;
  		}

			delay(50);
	}
}
