#pragma config(Motor,  port1,           right2,        tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           left2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           elev,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           right1,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          left1,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		motor[right1] = vexRT[Ch2];
		motor[right2] = vexRT[Ch2];
		motor[left1] = vexRT[Ch3];
		motor[left2] = vexRT[Ch3];
		motor[elev]=0;
		motor[claw]=0;
		if(vexRT[Btn7U]==1)
		{
			motor[elev]=127;
		}
		if(vexRT[Btn7D]==1)
		{
			motor[elev]=-127;
		}
		if(vexRT[Btn8U]==1)
		{
			motor[claw]=127;
		}
		if(vexRT[Btn8D]==1)
		{
			motor[claw]=-127;
		}
	}
}
