#pragma config(Sensor, in1,    potentio,       sensorPotentiometer)
#pragma config(Motor,  port1,           right1,        tmotorVex393_HBridge, openLoop, reversed, driveLeft)
#pragma config(Motor,  port2,           right2,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           claw_turn,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           claw_grip,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           left1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          left2,         tmotorVex393_HBridge, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//int rightside = 0;
//int leftside = 0;
bool reverse = false;

task main()
{
	for(;;){
		if (vexRT[Btn5U]==1){
			reverse=true;
		}else if (vexRT[Btn5D]==1){
			reverse=false;
		}

		//left side of the robot is controlled by the right joystick, Y-axis
		//rightm = -vexRT[Ch3];
		//right side of the robot is controlled by the left joystick, Y-axis
		//motor[leftm] = -vexRT[Ch2];

		if(!reverse){
			motor[left1] = vexRT[Ch3];
			motor[left2] = vexRT[Ch3];
			motor[right1] = vexRT[Ch2];
			motor[right2] = vexRT[Ch2];
		}
		else{
			motor[left1] = -vexRT[Ch2];
			motor[left2] = -vexRT[Ch2];
			motor[right1] = -vexRT[Ch3];
			motor[right2] = -vexRT[Ch3];
		}
		//Claw buttons
		if (vexRT[Btn7L] == 1)
			motor[claw_grip] = 100;
		else if(vexRT[Btn7R] == 1)
			motor[claw_grip] = -100;
		else
			motor[claw_grip] = 0;
		//Claw Turning
		motor[claw_turn] = 0;
		if (vexRT[Btn8U] == 1)
		{
			motor[claw_turn] = 100;
		}
		if(vexRT[Btn8D] == 1)
		{
			motor[claw_turn] = -100;
		}
		//Experimental: Automated Grabbing from ground
		if (vexRT[Btn5D]==1){
		for (;;){
				while (SensorValue(potentio)<4000){
					motor[claw_turn] = -100*((fabs(SensorValue(potentio)-4000))/4000)-20;
					wait(1);
				}
				while (SensorValue(potentio)>4050){
					motor[claw_turn] = +100*((fabs(SensorValue(potentio)-4050))/4050)+20;
					wait(1);
				}
				if (SensorValue(potentio)<=4050&&SensorValue(potentio)>=4000){
					motor[claw_turn]=0;
					motor[claw_grip]=100;
					wait(0.7);
					break;
				}
			}
		}
		//Experimental: Automated Release
		if (vexRT[Btn6U]==1){
			for (;;){
				while (SensorValue(potentio)<3400){

					motor[claw_turn] = -100*((fabs(SensorValue(potentio)-3400))/3400)-20;
					wait(1);
				}
				while (SensorValue(potentio)>3500){
					motor[claw_turn] = +100*((fabs(SensorValue(potentio)-3500))/3500)+20;
					wait(1);
				}
				if (SensorValue(potentio)<=3500&&SensorValue(potentio)>=3400){
					motor[claw_turn]=0;
					motor[claw_grip]=100;
					wait(0.7);
					break;
				}
			}
		}
	}
}
