#pragma config(Sensor, dgtl1,  touch,          sensorTouch)
#pragma config(Motor,  port1,           motor1,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
// Bumper is set to dgtl port 1, as it is a digital sensor.

// This code only works autonomously under USB-Only Mode!
task main()
{
	for(;;){ //Most efficient method of infinite loop
	untilBump(dgtl1); //See RobotC documentation for more details
	motor[motor1] = 127;
	wait(0.5); //For human lag when pressing button, making sure button is only pressed once in 0.5 secs.
  //Robot will not do anything for 0.5 secs after sensing bump on bumper.
	//wait (100000000);
	untilBump(dgtl1);
	motor[motor1] = 0; //Press second time to stop robot motor.
	wait(0.5);
	}
}
